site_name: DSSG Hitchhickers guide
theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'deep orange'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo:
    icon: 'bubble_chart'


docs_dir: sources
repo_name: 'dssg/hitchhikers-guide'
repo_url: https://github.com/dssg/hitchhikers-guide
site_description: ''

extra:
  social:
    - type: 'github'
      link: 'https://github.com/dssg/hitchhikers-guide'
    - type: 'twitter'
      link: 'https://twitter.com/datascifellows'
    - type: 'linkedin'
      link: 'https://linkedin.com/company/center-for-data-science-and-public-policy-university-of-chicago'

markdown_extensions:
  - admonition
  - toc:
      permalink: True
      baselevel: 2
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.extrarawhtml
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - "js/mermaid.min.js"

pages:
  - Home: index.md
  - DSSG Manual:
      - Code of conduct: dssg-manual/conduct-culture-and-communications/README.md
      - Summer overview: dssg-manual/summer-overview/README.md
  - Curriculum:
      - Intro: curriculum/README.md
      - Before you start: curriculum/0_before_you_start/README.md
      - Getting and keeping data: curriculum/1_getting_and_keeping_data/README.md
      - Data exploration and analysis: curriculum/2_data_exploration_and_analysis/README.md
      - Modeling and ML: curriculum/3_modeling_and_machine_learning/README.md
      - Programming best practices: curriculum/4_programming_best_practices/README.md
      - Presentations and communications: curriculum/5_presentations_and_communications/README.md
